{
  "name": "Получение заказов рядом с ближайшей станцией",
  "status": "failed",
  "statusDetails": {
    "message": "AssertionError: Не удалось принять заказ 174355 курьером 345293: 409, {'code': 409, 'message': 'Этот заказ уже в работе'}\nassert 409 == 200\n +  where 409 = <Response [409]>.status_code",
    "trace": "@pytest.fixture(scope=\"function\")\n    def setup_orders_for_list_tests():\n        # Setup\n        courier_helper = CourierHelper()\n        order_helper = OrderHelper()\n        # Создание курьера\n        new_courier = courier_helper.create_courier()\n        assert new_courier, \"Ошибка при создании курьера.\"\n        print(f\"Курьер создан: {new_courier}\")\n        # Логин курьера для получения id\n        courier_id = courier_helper.login_courier(new_courier[\"login\"], new_courier[\"password\"])\n        assert courier_id, \"Ошибка при логине курьера.\"\n        print(f\"Курьер вошел в систему с ID: {courier_id}\")\n        # Создание 5 заказов\n        orders = []\n        for _ in range(5):\n            order_data = generate_order_data()\n            response = order_helper.create_order(order_data)\n            assert response.status_code == 201, f\"Не удалось создать заказ: {response.json()}\"\n            track = response.json()['track']\n            print(f\"Создан заказ с треком: {track}\")\n            # Нужна задержка, иначе api не успевает обработать все заказы\n            time.sleep(5)\n            # Получение информации о заказе по его номеру (track)\n            order_details = order_helper.get_order_by_track(track)\n            assert order_details.status_code == 200, f\"Не удалось получить детали заказа: {order_details.json()}\"\n            order_id = order_details.json()[\"order\"][\"id\"]\n            print(f\"Получены детали заказа. ID заказа: {order_id}\")\n            orders.append({\"track\": track, \"id\": order_id})\n    \n        assert len(orders) == 5, \"Не все заказы были успешно созданы.\"\n        # Принятие курьером 3 заказов\n        for order in orders[:3]:\n            response = order_helper.accept_order(order['id'], courier_id)\n>           assert response.status_code == 200, f\"Не удалось принять заказ {order['id']} курьером {courier_id}: {response.status_code}, {response.json()}\"\nE           AssertionError: Не удалось принять заказ 174355 курьером 345293: 409, {'code': 409, 'message': 'Этот заказ уже в работе'}\nE           assert 409 == 200\nE            +  where 409 = <Response [409]>.status_code\n\ntests\\conftest.py:86: AssertionError"
  },
  "attachments": [
    {
      "name": "stdout",
      "source": "43ca9e15-3abb-4978-b868-37fce166f6a2-attachment.txt",
      "type": "text/plain"
    }
  ],
  "start": 1720480313299,
  "stop": 1720480313299,
  "uuid": "7f211c62-1292-4fec-8473-a4b0932bb7fd",
  "historyId": "e9d2299e371bf67c13a86796fc6ae64a",
  "testCaseId": "e9d2299e371bf67c13a86796fc6ae64a",
  "fullName": "tests.tests_main.tests_orders.test_order_list.test_list_orders_positive.TestListOrdersPositive#test_get_orders_with_nearest_station",
  "labels": [
    {
      "name": "story",
      "value": "Позитивные сценарии"
    },
    {
      "name": "feature",
      "value": "Получение списка заказов"
    },
    {
      "name": "tag",
      "value": "positive"
    },
    {
      "name": "parentSuite",
      "value": "tests.tests_main.tests_orders.test_order_list"
    },
    {
      "name": "suite",
      "value": "test_list_orders_positive"
    },
    {
      "name": "subSuite",
      "value": "TestListOrdersPositive"
    },
    {
      "name": "host",
      "value": "PandaPC"
    },
    {
      "name": "thread",
      "value": "86244-MainThread"
    },
    {
      "name": "framework",
      "value": "pytest"
    },
    {
      "name": "language",
      "value": "cpython3"
    },
    {
      "name": "package",
      "value": "tests.tests_main.tests_orders.test_order_list.test_list_orders_positive"
    }
  ]
}